version: "3"

services: 
  media:
    build: 
      context: ./media
      dockerfile: ./Dockerfile
    volumes: 
      - website:/website/dist

  bot:
    ports:
      - "3000:3000"
    build:
      context: ./blazy-manager-bot
      dockerfile: ./Dockerfile
    restart: unless-stopped

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - website:/website/dist
    depends_on:
      - bot
      - media

volumes: 
  website:
    driver: local