version: "3"

services: 
  media:
    build: 
      context: ./media
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    restart: unless-stopped

  bot:
    ports:
      - 3000:3000
    build:
      context: ./blazy-manager-bot
      dockerfile: ./Dockerfile
    restart: unless-stopped

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=hello@blazy.media
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./user_conf.d:/etc/nginx/user_conf.d
      - nginx_secrets:/etc/letsencrypt

volumes: 
  nginx_secrets: